### ISSUE TITLE
PR #9932 Into UE Was Reverted

### ISSUE THREAD

**Issue by MattEqualsCoder** [octobuild/octobuild#100]
Hello,

Just as an FYI, PR [#9932 - Fix action graph copy action on non-Windows platforms](https://github.com/EpicGames/UnrealEngine/pull/9932) was reverted in [this commit](https://github.com/EpicGames/UnrealEngine/commit/ad5c1243b006935c04ca0a8b66843de5c38fa39f).

Not sure if you all want to actually try to make another attempt to push out to UE or not, but you may want to at least update the README.md as it's no longer included in 5.2 and above it seems.

**Comment by slonopotamus** [comment]
I'm not sure it was reverted. In original code, there was unmatched quote. Now it _looks_ matching, though it is really hard to read :D

**Comment by MattEqualsCoder** [comment]
Ahhh, my mistake. It looked like what it was before, but I missed that detail. Sorry about that!

I haven't tried with 5.3 yet myself, just on 5.2. 

Think this can be closed out, then! Appreciate the quick response and sorry again for the false alarm.

**Comment by slonopotamus** [comment]
No problem. I'm also on 5.2 yet. There were reports about issues with 5.3 on Windows, but none yet for Linux.
