### ISSUE TITLE
is there a way to disable octobuild once installed?

### ISSUE THREAD

**Issue by cosmoselodie** [octobuild/octobuild#115]
hey there - i'm in a world where we're upgrading from UE 4.27 to UE5.3.  As soon as I install octobuild, it starts acting on my 4.27 builds when I only want to use it for my 5.0+ builds.  Is there an environment var or some way I can disable octobuild?  At present the best workflow I have is to uninstall it everytime i need to build 4.27, which is pretty rough on me.  thanks in advance.

**Comment by slonopotamus** [comment]
You can pass `-noxge` to both UBT and UAT.
