### ISSUE TITLE
does octobuild support cross-compilation on windows?

### ISSUE THREAD

**Issue by cosmoselodie** [octobuild/octobuild#116]
hey - i see there's linux support.  Can I use octobuild to cross compile to linux from a windows host?

I tried with the vanilla UnrealServer in 5.2 but got some weird errors.  I didn't see any mention of cross compiling in the readme so i thought I would ask.

**Comment by slonopotamus** [comment]
I never tested that. Possibly needs minor fixes.

**Comment by slonopotamus** [comment]
See #117

**Comment by cosmoselodie** [comment]
womp.  

any plans to fix it?
