### ISSUE TITLE
Enable/Disable Octobuild using environment variable (or some machine global setting).

### ISSUE THREAD

**Issue by ldemers777** [octobuild/octobuild#119]
Following issues/questions:

- https://github.com/octobuild/octobuild/issues/101
- https://github.com/octobuild/octobuild/issues/115

I would still prefer having a more passive way to control whether Octobuild is active (or not) like an **environment variable** (which would also be consistent with the other configurations). 

I am considering installing it on our build farms/machines for CI purposes but implementing the `-NoXGE` flag per-build configs/cases would be much less convenient. 

I would prefer a way to disable it by default and only enable it for a few cases. Without this, we're likely to end our consideration for Octobuild.

Are there any limitations to not implementing it this way (e.g. performance hit to check the var every time)?

Thanks

**Comment by slonopotamus** [comment]
There's also `bAllowXGE` option in `BuildConfiguration.xml`: https://dev.epicgames.com/documentation/en-us/unreal-engine/build-configuration-for-unreal-engine#buildconfiguration

> which would also be consistent with the other configurations

I'm not sure what you're talking about.

> Are there any limitations to not implementing it this way

Well, this is the way Epic Games implemented the option to disable IncrediBuild (which we mimic) in their tools.

**Comment by ldemers777** [comment]
> I'm not sure what you're talking about.

For the other (documented) configurations, I was referring to:

![image](https://github.com/octobuild/octobuild/assets/89998854/27ac896f-2d8b-45b6-810d-4501bf83597e)
Ref: https://github.com/octobuild/octobuild/blob/main/README.adoc#environment-variables

**Comment by ldemers777** [comment]
Like https://github.com/octobuild/octobuild/issues/115 mentions, `As soon as I install octobuild, it starts acting...`.

Our build machine images support many projects with hundreds of build configurations (jobs/pipelines) and the build machines are dynamically provisioned from those images. The image is where we install all required (and optional) dependencies. Octobuild could be one of those optional dependencies and be enabled only for some specific build configurations (controlled at the environment bootstrap of the build configuration) but we don't want it to act at all otherwise (by default). So having an environment variable, we could install Octobuild on our main build machine images but set the environment variable to "disabled".

It's more convenient to activate it on a few build configurations (jobs/pipelines) than disabling it in every tool/location that invokes UBT/UAT. Lastly, it's also easier to dynamically control environment variables, than let's say, configuration files or UBT/UAT parameters (at least, in our case but I suspect I am not the first one asking for similar reasons).

Most of our build machines are disposed of after a build job (so they get void along with their cache). Having these machines fill a cache that they will never use will impair performance for nothing. However, we have some build configurations/pipelines where we maintain fleets of machines in a more persistent way and for which Octobuild could be proven impactful.

Hopefully, that extensive context can help better understand the situation/need.

Thanks

**Comment by slonopotamus** [comment]
If you want a per-machine setting, there's an option to disable "Octobuild Agent" Windows service. This will indicate UE that it should not use octobuild at all. But yeah, I can implement a "don't cache anything" env variable for per-job control.

**Comment by ldemers777** [comment]
Yes both `don't cache anything` and `don't use any cache`  would be helpful. That would give even more control in case we only want one of the two and I assume disabling both is the same as disabling Octobuild (as far as Octobuil only features local cache... for now).
