### ISSUE TITLE
Debian Package Relies on Old libssl Version

### ISSUE THREAD

**Issue by MattEqualsCoder** [octobuild/octobuild#122]
I'm running on the latest version of Linux Mint, and I tried installing the .deb package both from the repository and from the manual download. Unfortunately, it failed due to the following message:

```
The following packages have unmet dependencies:
 octobuild : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Looking into it, it appears I have libssl v3.0.13, which I'm guessing is at the point of not being backwards compatible?

Building through Homebrew worked just fine, though.

**Comment by slonopotamus** [comment]
Which package are you using? I believe that [jammy](https://cloudsmith.io/~octobuild/repos/octobuild/packages/?q=version:latest+and+distribution:jammy) (Ubuntu 22.04) one works with libssl3 properly.

**Comment by MattEqualsCoder** [comment]
Ah, whoops. Good call, I completely overlooked that there were two packages. My bad.
