### ISSUE TITLE
Is it possible to share the cache between machines?

### ISSUE THREAD

**Issue by t4eman** [octobuild/octobuild#126]
During the Packer image build process, I generate the build cache by performing an initial build and storing it locally on the drive. However, when the build machine is initialized for a new build, it doesn't use the existing cache (even though environment variables point to the local cache location). Instead, it generates a new cache from scratch. If I run the build again on the same machine, it correctly reuses the previously generated cache.

I'm trying to figure out if it's possible to make the cache reusable across different machines, rather than generating a new cache each time.

**Comment by slonopotamus** [comment]
Generally, it should be possible to transfer cache between machine, though you need to be careful.

https://github.com/octobuild/octobuild/blob/1.5.0/src/compiler.rs#L616-L662

Caching depends on
* Absolute path to sources
* Compiler flags
* Compiler version

**Comment by t4eman** [comment]
In the code it looks like it generates a hash… Could the hash be different between machines and why it doesn’t see the existing cache? Cause everything is exactly the same other then the machine.

**Comment by slonopotamus** [comment]
This hash is used as a key to lookup in the cache.

**Comment by t4eman** [comment]
Ah okay. Caching to a network share seems to work. Which is awesome! Thank you!
