### ISSUE TITLE
What do I need to make this work in my LAN?

### ISSUE THREAD

**Issue by juaxix** [octobuild/octobuild#85]
I have so many questions.
- I wonder if I need to install VS22 (the one I use) in all the machines that will work as agents
- do you need to open the port `3000` (or the one I use) in the firewall for them all?
- do you need to also install Unreal Engine (same engine for all agents) , in the same dir?

how does the coordinator knows how to build the objects and what compiler/files to use?

this is my config:
`{
	"cache": "C:\\Users\\Juaxix\\AppData\\Local\\octobuild\\cache",
	"cache_limit_mb": 120000,
	#coordinator: null,
	"coordinator_bind": "192.168.1.132:3000",
	#"process_limit": 21,
	"run_second_cpp": true,
	"use_response_files": true
}`

that means that all agents with the same config (except for the cache folder) will pick up the coordinator?
Thanks!

**Comment by slonopotamus** [comment]
Currently octobuild only supports local mode. So, you just install it and Unreal Engine picks up `xgConsole.exe` from octobuild and lets it cache builds.

Distributed mode is unfinished and has several unsolved issues. One of them, as you pointed out, it isn't clear how compiler is supposed to appear on builder node.

**Comment by slonopotamus** [comment]
For now, please refer to https://github.com/octobuild/octobuild/blob/master/README.adoc for supported platforms/options.
