### ISSUE TITLE
unknown command line arguments: `/external:W0`, `/external:I` when using VS2022

### ISSUE THREAD

**Issue by markusstephanides** [octobuild/octobuild#88]
Hi!

Just wanted to try this promising looking tool (version 0.5.2) but upon compiling my game with it (Engine Source Build based on UE 5.1, VS 2022), these errors appear:

![image](https://user-images.githubusercontent.com/6057570/223946247-4524661d-745a-4c90-a684-47452e91fcc3.png)

What could the issue be here? It looks like the build still succeeds at the end and I can launch the game.

Thank you very much!

**Comment by slonopotamus** [comment]
> It looks like the build still succeeds at the end and I can launch the game.

Yeah, this is by design. When octobuild sees compiler flags that it doesn't understand, it disables caching but still runs the task normally.

These `/external` flags come from here: https://github.com/EpicGames/UnrealEngine/blob/5.1.1-release/Engine/Source/Programs/UnrealBuildTool/Platform/Windows/VCToolChain.cs#L177-L185

Which means, you're using VS2022 that I didn't tests against.

**Comment by slonopotamus** [comment]
@markusstephanides could you please try `.msi` from [this commit](https://github.com/octobuild/octobuild/actions/runs/4373968132)? If that works for you, I'll roll out a new release with the fix.

**Comment by markusstephanides** [comment]
Thank you very much for the quick response and the quick fix, it works now!

Are there any downsides to setting the cache directory to a shared network drive? Or is it recommended to only use a local cache for now?

**Comment by slonopotamus** [comment]
> Are there any downsides to setting the cache directory to a shared network drive?

If you're in a trusted environment (i.e. malicious user cannot put bad stuff into cache), that workflow definitely could work.

**Comment by markusstephanides** [comment]
Yeah it's only available within the local network and I was looking to share the cache between team members and build servers to speed up compilation times, would that work that way? 

Also does Octobuild also accelerate shader compilation times or only C++ code compilation?

**Comment by slonopotamus** [comment]
> to speed up compilation times, would that work that way?

Definitely depends on your network speed. I guess you should do some benchmarks. I'm only using local caching, so have no idea how profitable your approach will be.

> Also does Octobuild also accelerate shader compilation times or only C++ code compilation?

Only C++ for now.

**Comment by slonopotamus** [comment]
Fix for this issue included in octobuild 0.5.3 that is currently [being released](https://github.com/octobuild/octobuild/actions/runs/4374347964). Note that publishing to WinGet/Chocolatey/Homebrew will take several hours.
