### ISSUE TITLE
ue5-main: Found unknown command line arguments: ["-driver-mode"]

### ISSUE THREAD

**Issue by negril** [octobuild/octobuild#91]
https://github.com/EpicGames/UnrealEngine/commit/547593db87ff7b224fb43715aaf997a5aae5aab8 forcibly added `--driver-mode=g++` to the compiler call making octobuild complain about it being an unknown command line argument and causing it to bail out.

**Comment by slonopotamus** [comment]
Fixed in octobuild 0.5.5.
