### ISSUE TITLE
PCH is not recompiled after MSVC update

### ISSUE THREAD

**Issue by RedwanFox** [octobuild/octobuild#95]
Way to reproduce:
1. Create project with PCH enabled. Compile it with msvc ver 1
2. update msvc to ver 2
3. Rebuild project

Result: [c1853](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1853?view=msvc-170) compile error. Project cleanup doesn't help. Only octobuild cache cleanup

**Comment by samaursa** [comment]
Same problem here. Project Cleanup/Rebuild does not help in this case.
