### ISSUE TITLE
Found unknown command line arguments: ["/utf-8", "/permissive-"] when using VS2022

### ISSUE THREAD

**Issue by DudeRenderer** [octobuild/octobuild#98]
Hi
I tried to use this tool to compiling Unreal Engine Source based on ue5-main, VS2022

![image](https://github.com/octobuild/octobuild/assets/33353769/a1b95562-74f9-464d-862e-498a9f1436f5)

What is the cause of this error?
BTW, Does this tool need to recompile the project once and compile it later to get the boost, or does it do it the first time?

**Comment by slonopotamus** [comment]
> What is the cause of this error?

Lack of support for these flags in octobuild. Fixed in 38a41e4e4ac5b017a815d6ad3d345b6123b22759. The warning means that cache won't be used.
